$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
        autoplay:true,
        autoplayTimeout:3000,
        dots:true,
        dotsEach:true,
        loop:true,
        margin:10,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:true
            },
            600:{
                items:1,
                nav:false
            },
            1000:{
                items:1,
                margin:3,
                nav:false,
                loop:true
            }
        }
    })
  });
  